### ISSUE TITLE
Give us choices to disable the "GiveBookOnFirstJoinProcedure" event

### ISSUE THREAD

**Issue by ColdTearsYY** [Y3Z0N/theabyss#26]
### Describe the Suggestion

The mod is awesome for single players and multiplayers, but it can be annoying that in the config file we can't disable the book-giving event, which sometimes cause crashes.

### Additional Context

A PREVIOUS ERROR REPORTED ON SERVER:
Description: Exception in server tick loop

java.lang.AbstractMethodError: Method net/minecraft/command/ICommandSource$1.bridge$getBukkitSender(Lnet/minecraft/command/CommandSource;)Lorg/bukkit/command/CommandSender; is abstract
	at net.minecraft.command.ICommandSource$1.bridge$getBukkitSender(SourceFile) ~[?:?] {re:classloading}
	at net.minecraft.command.CommandSource.getBukkitSender(CommandSourceMixin.java:559) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at org.bukkit.craftbukkit.v1_16_R3.command.BukkitCommandWrapper.test(BukkitCommandWrapperMixin.java:39) ~[arclight:arclight-1.16.5-1.0.21-12996b7] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:BukkitCommandWrapperMixin,pl:mixin:A}
	at org.bukkit.craftbukkit.v1_16_R3.command.BukkitCommandWrapper.test(BukkitCommandWrapperMixin.java:1) ~[arclight:arclight-1.16.5-1.0.21-12996b7] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:BukkitCommandWrapperMixin,pl:mixin:A}
	at com.mojang.brigadier.tree.CommandNode.handler$zkm000$on(CommandNodeMixin.java:545) ~[?:?] {re:mixin,re:classloading,pl:mixin:A,re:mixin}
	at com.mojang.brigadier.tree.CommandNode.canUse(CommandNodeMixin.java) ~[?:?] {re:mixin,re:classloading,pl:mixin:A,re:mixin}
	at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[?:?] {re:classloading,re:mixin}
	at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.command.Commands.func_197059_a(CommandsMixin.java:209) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:command.CommandsMixin,pl:mixin:A}
	at net.yezon.theabyss.procedures.GiveBookOnFirstJoinProcedure$1$1.run(GiveBookOnFirstJoinProcedure.java:219) ~[theabyss:?] {re:classloading,pl:eventbus:A}
	at net.yezon.theabyss.procedures.GiveBookOnFirstJoinProcedure$1$1.tick(GiveBookOnFirstJoinProcedure.java:158) ~[theabyss:?] {re:classloading,pl:eventbus:A}
	at net.minecraftforge.eventbus.ASMEventHandler_1597__tick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:120) ~[forge:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:828) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:853) [?:1.8.0_312] {}

**Comment by Y3Z0N** [comment]
You use a invalid/modified forge version where bukkit is installed. there will be no fix from my side. report that issue to the dev team of this bukkit mod/version

**Comment by ColdTearsYY** [comment]
I don't mean to let you to fix the bug.I just want a choice to disable giving-book-on-first-join in the config file.I will make my words clear so that you might understand what I am talking about.

**Comment by Y3Z0N** [comment]
thats already added set LPM mode to „true“

**Comment by ColdTearsYY** [comment]
thanks a lot
